### ISSUE TITLE
i need a little help 

### ISSUE THREAD

**Issue by AtomicGaming666** [Assistants-Center/Discord.js-Web-Dashboard#43]
im getting this error when ever i try to use the Dashboard my bot dont even start 

![image](https://user-images.githubusercontent.com/39306849/153697006-0c2eaa7a-7dd0-445f-9f22-d239af2f40e1.png)

**Comment by AtomicGaming666** [comment]
and dont wary about the IP thats invalid its just what shows on the panel

**Comment by AtomicGaming666** [comment]
just in case

/home/container/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://dbd-external-stats.assistants.ga/registerProject failed, reason: getaddrinfo EAI_AGAIN dbd-external-stats.assistants.ga
    at ClientRequest.<anonymous> (/home/container/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

there is the error

**Comment by breftejk** [comment]
Please make sure ur using the latest version after domain change.

**Comment by AtomicGaming666** [comment]
i'm using the latest

**Comment by breftejk** [comment]
2.2.23?

**Comment by AtomicGaming666** [comment]
yes

**Comment by AtomicGaming666** [comment]
hello i fix it ;)

**Comment by AtomicGaming666** [comment]
im getting a new problem now 

/home/container/bot.js:234
 const Dashboard = new DBD.Dashboard({
                   ^

TypeError: DBD.Dashboard is not a constructor
    at Object.<anonymous> (/home/container/bot.js:234:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

**Comment by breftejk** [comment]
![image](https://user-images.githubusercontent.com/62174194/153703240-5f7c4918-8dc1-40d9-90dc-fb229f6411ef.png)

**Comment by breftejk** [comment]
(Don't do step 1, you are already on v2)

**Comment by AtomicGaming666** [comment]
ya im just trying to figer this out xD

**Comment by breftejk** [comment]
![image](https://user-images.githubusercontent.com/62174194/153703703-3c544780-d157-40d7-9990-5cc6970a2cad.png)

**Comment by breftejk** [comment]
ignore altometra and capriham, just use dark

**Comment by AtomicGaming666** [comment]
yours is done lot dif then mine i did not code all of my bot so i dont realy know what im doing

**Comment by AtomicGaming666** [comment]
getting 
/home/container/bot.js:239
const Dashboard = new DBD.Dashboard({
                  ^

TypeError: DBD.Dashboard is not a constructor
    at Object.<anonymous> (/home/container/bot.js:239:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
    
again

**Comment by breftejk** [comment]
That's bcse ur not awaiting useLicense and doing DBD.Dashboard = DBD.UpdatedClass() before creating Dashboard

**Comment by AtomicGaming666** [comment]
i do not know what you are talking about

**Comment by breftejk** [comment]
"i did not code all of my bot"
Which OpenSource project are you using?

**Comment by AtomicGaming666** [comment]
one of my frends game me there bot code and he helped me set it started im just like realy new to javascript

**Comment by breftejk** [comment]
Ask him/her/they to help you, you really don't understand what I'm saying, like you said - 'you're like really new to javascript'. He/she/they will understand what I'm saying and help (aKa sponfeed tho) you.

**Comment by AtomicGaming666** [comment]
i dont like bing called a spoonfeeder unlike others i try

**Comment by breftejk** [comment]
I see and that's true, but only spoonfeed will help you at this point, sadly.

**Comment by AtomicGaming666** [comment]
im learning slowly just some thinks just go over my head atm but thx for trying

**Comment by breftejk** [comment]
All you really need to do is make sure Dashboard is inited in this way:
![image](https://user-images.githubusercontent.com/62174194/153704298-7cf45ebf-ce61-4012-8e24-801c53130654.png)
When you'll figure this out, it will be fixed.

**Comment by AtomicGaming666** [comment]
like atm i fixed that problem but now im getting 
SyntaxError: await is only valid in async functions and the top level bodies of modules

and idk how to make a async functions

**Comment by breftejk** [comment]
Ignoring Altometra, Caprigam and `const DarkDashboard = require('dbd-dark-dashboard');` for you.

**Comment by breftejk** [comment]
> like atm i fixed that problem but now im getting SyntaxError: await is only valid in async functions and the top level bodies of modules
> 
> and idk how to make a async functions

you need to move your code to an async function tho:

```js
(async()=>{
// YOUR CODE
});
```

**Comment by AtomicGaming666** [comment]
OMG I GOT IT thx thats all i needed to know 

souldof sead that from the start lol but again THX
